$(document).ready(function(){

	var liste = [
    	
		"Litige avec un artisan",
		"Litige avec un voisin",
		"Litige avec un garagiste",
		"Litige voiture",
		"Litige moto",
		"Litige avec un plombier",
		"Litige avec un peintre",
		"Litige maçon",
		"Litige avec un maçon",
		"Litige toiture",
		"Litige toiturier",
		"Caution",
		"Litige bail",
		"Litige baux",
		"Problème bail d'habitation",
		"Litige caution",
		"Caution non restitutuée",
		"Dépôt de garantie non restitutuée",
		"Dépôt de garantie",
		"Litige avec un opérateur téléphonique",
		"Litige orange",
		"Litige free",
		"Litige bouygues",
		"Litige avec voyagiste",
		"Litige avec agence de voyage",
		"Litige avec compagnie aérienne",
		"Litige avec transporteur",
		"Litige avec air france",
		"Litige avec trains",
		"Litige avec avions",
		"Litige avec un voyagiste",
		"Litige avec une agence de voyage",
		"Litige avec une compagnie aérienne",
		"Litige avec un transporteur",
		"Litige avec la SNCF",
		"Litige achats sur internet",
		"Litige achats web",
		"Litige e-commerce",
		"Litige ventes sur inerent",
		"Litige ventes internet",
		"Litige achats en ligne",
		"Litige ventes en ligne",
		"Litige site internet",
		"Litige commande",
		"Commande",
		"Colis perdu",
		"Probleme achat sur internet",
		"Probleme achats sur internet",
		"Litige entre pariculiers",
		"Litiges arbre mal planté",
		"Bruit de voisinage",
		"Tapagisme",
		"Problème de remboursement",
		"Rembousements achats sur internet",
		"Reconnaissance de dette",
		"Litige banque",
		"Litige assurance",
		"Litige assureur",
		"Litige avec banque",
		"Litige avec assurance",
		"Litige avec assureur",
		"Litige avec une banque",
		"Litige avec une assurance",
		"Litige avec un assureur",
		"Litige crédit",
		"Crédit immobilier",
		"Crédit foncier",
		"Crédit consommation",
		"Crédit a la consommation",
		"Crédit à la consommation",
		"Crédit auto",
		"Crédit moto",
		"Crédit automobile",
		"Problème prêt immobilier",
		"Problème prêt auto",
		"Litige prêt immobilier",
		"Litige prêt auto",
		"Remboursement de crédit",
		"Remboursement de prêt",
		"Problème de pension alimentaire",
		"Problème de paiment de la pension alimentaire",
		"Pension alimentaire non payée",
		"Pension alimentaire non versée",
		"Réévalutation de la pension alimentaire",
		"Augmentation de la pension alimentaire",
		"Diminution de la pension alimentaire",
		"Suppression de la pension alimentaire",
		"Calcul de revalorisation de la pension alimentaire",
		"Droit de garde des enfants",
		"Droit de visite et d'hébergement",
		"Droit du père",
		"Droit de la mère",
		"Droit des grands parents",
		"Garde partagée",
		"Garde alternée",
		"Droit d'hébergement",
		"Droit de visite et dhebergement",
		"Droit de visite et d'hebergement",
		"Calcul du montant de la pension alimentaire",
		"Saisir le JAF",
		"Saisir le juge aux affaires familiales",
		"Juge aux affaires familiales",
		"Juge affaire familiales",
		"Juge des affaires familiales",
		"Juge des affaires familiale",
		"Juge des enfants",
		"Juge enfants",
		"Juge des affaires de la famille",
		"Juge familiale",
		"Dossier famille",
		"Dossier juge affaires familiales",
		"Juge affaires familiales",
		"Obligation alimentaire",
		"Obligation d'aliments",
		"Obligation aliments",
		"Obligation parentale",
		"Droits des parents",
		"Parents",
		"Mère",
		"Père",
		"Autorité parentale",
		"Autorité parentale conjointe",
		"Autorité parentale exclusive",
		"Procès-verbal",
		"Contestation PV excès de vitesse",
		"Radar mobile",
		"Radar auto",
		"Radar automatique",
		"Flash",
		"Contrôle vitesse",
		"Contestation vitesse",
		"PV exces de vitesse amende",
		"Contester les points permis",
		"Retrait points de permis",
		"Licenciement abusif",
		"Licenciement faute",
		"Licenciement pour faute",
		"Licenciement faute grave",
		"Licenciement faute lourde",
		"Licenciement pour faute grave",
		"Licenciement pour faute lourde",
		"Licenciement emploi",
		"Perte d'emploi",
		"Je suis viré",
		"Je suis virée",
		"Je me suis fait virer",
		"Rupture conventionnelle",
		"Rupture contrat de travail",
		"Contrat de travail",
		"Indemnités salaires",
		"Salaires",
		"Salaires impayés",
		"Salaires non payés",
		"Salaires non versé",
		"Salaires non versés",
		"Salaires heure supplémentaire",
		"Calcul salaire",
		"Heures supplémentaires",
		"Litige employeur",
		"Litige patron",
		"Litige travailleur",
		"Litige salarié",
		"Harcèlement",
		"Harcèlement moral",
		"Harcèlement psychologique",
		"Démission",
		"Contestation licenciement abusif",
		"Heures non payés",
		"Conseil  de prud'hommes",
        "Accident du travail",
        "Fautes inexcusables",
        "Reconnaissance de maladie professionnelle",
        "Maladie professionnelle",
        "Cotisations",
        "Cotisations RSI",
        "Cotisations sociales",
        "Cotisations URSSAF",
        "Cotisations CARSAT",
        "Cotisations CPAM",
        "Opposition à contrainte",
    ];

	$('#recherche').autocomplete({
	    source : liste,
	    minLength : 2
	});

});

		
